
- name: Configure r1
  hosts: r1
  become: yes

  tasks:
  - name: Deploy Configuration To r1
    nclu:
        commit: true
        description: "Deploy interface configuration"
        commands:
            - add interface swp1 ip address 192.168.100.1/30
            - add ospf network 192.168.100.0/30 area 0.0.0.0

- name: Configure r2
  hosts: r2
  become: yes

  tasks:
  - name: Deploy Configuration To r2
    nclu:
        commit: true
        description: "Deploy interface configuration"
        commands:
            - add interface swp1 ip address 192.168.100.2/30
            - add interface swp2 ip address 192.168.100.5/30
            - add ospf network 192.168.100.0/30 area 0.0.0.0
            - add ospf network 192.168.100.4/30 area 1.1.1.1

- name: Configure r3
  hosts: r3
  become: yes

  tasks:
  - name: Deploy Configuration To r3
    nclu:
        commit: true
        description: "Deploy interface configuration"
        commands:
            - add interface swp2 ip address 192.168.100.6/30
            - add loopback lo ip address 192.168.200.1/32
            - add routing route 172.18.0.0/24 lo 10
            - add routing route 172.18.1.0/24 lo 10
            - add routing route 172.18.2.0/24 lo 10
            - add routing route 172.18.3.0/24 lo 10
            - add ospf network 192.168.100.4/30 area 1.1.1.1
            - add routing route 172.18.0.0/22 lo 100
            - add routing prefix-list ipv4 allowsummary seq 5 permit 172.18.0.0/21
            - add routing prefix-list ipv4 allowsummary seq 10 deny any
            - add routing route-map testmap permit 10 match ip address prefix-list allowsummary
            - add routing route-map testmap deny 20
            - add ospf redistribute static route-map testmap
